### ISSUE TITLE
OCR is terrible when imported into Paperless

### ISSUE THREAD

**Issue by cfredericksen** [zix99/virtual-cups-printer#3]
I deployed this yesterday and its awesome. One thing I noticed is that Paperless OCR'd the PDFs and they are unreadable. Any experience with CUPS and formatting the virtual printer to allow for better OCR?

**Comment by zix99** [comment]
Hey -- would you be able to provide an example?  I've been using this for a while, and OCR seems fine for me. Maybe it's a paperless setting?

**Comment by cfredericksen** [comment]
@zix99 Thanks for the reply. I did end up fixing and it was paperless related. I changed PAPERLESS_OCR_MODE = force and this resolved the issue. Closing now.
